### PR TITLE
Launch shared before publish

### PR DESCRIPTION
**Pull request by kosssi**

### CODE REVIEW

**Comment by timkelty** [comment]
Seems reasonable, was there a specific issue this was causing?

**Comment by timkelty** [comment]
Related to this: https://github.com/timkelty/shipit-shared/issues/13

I'll merge for now, but I may make this optional all together in the future.

**Comment by kosssi** [comment]
@timkelty can you publish it in npm ?

**Comment by timkelty** [comment]
Pushed to NPM: shipit-shared@3.1.0

**Comment by kosssi** [comment]
thanks ;)

**Pull request merged**
