### PR TITLE
Copy file from release to shared if it does not exist yet

### PR DESCRIPTION
**Pull request by gjanvier**
Hi !
Could this help for your #23 issue ?

### CODE REVIEW

**Comment by timkelty** [comment]
Sorry for the delay, good to see tests are passing now.

Can you briefly outline your use-case and how you're using this feature? Just curious.

**Comment by timkelty** [comment]
I have this merged into master.

When you get a chance let me know how/why you're using this feature. I want to have a good idea of how people are using this so I can update the readme appropriately.

**Comment by gjanvier** [comment]
Hi,

I am trying to reproduce capifony behaviour using shipit. (Basically because I would need to customize capifony and don't know ruby, and I already know/use nodejs with grunt to do a lot of things on my project).

Let me quote capifony doc (http://capifony.org/), my server will look like:

```
`-- /var/www/my-app.com
|-- current → /var/www/my-app.com/releases/20100512131539
|-- releases
|   `-- 20100512131539
|   `-- 20100509150741
|   `-- 20100509145325
`-- shared
   |-- web
   |    `-- uploads
   |-- log
   `-- config
       `-- databases.yml
```

I use shipit-share for some folders that must be shared between released (mainly logs) and some config files. My deployment script (grunt and shipit) generates a config file (.yml) : at the 1st run, that file must be stored in a shared folder, and linked in any release to come.

**Comment by timkelty** [comment]
Right, this is the standard Capistrano/Capifony setup. I was curious how you are using this specific feature (Copy file from release to shared if it does not exist yet).

The expected setup for your structure would be to have `shared/web/uploads`, `log`, and `config/database.yml` git-ignored and listed as paths in your shipit-shared options.

Wanting this feature suggested you have some of those _not_ git-ignored. I'm curious what the reasoning for that is.

Thanks!

**Pull request merged**
